# This is an example configuration for the delta-s3-loader lambda
---
sources:
# This entry maps the existing S3 structure into a delta table named
# `logs.audit_logs` which will be date stamp partitioned
#
# └── simple
#     └── date=2021-04-16
#         └── auditlog-1234.json
  - bucket: 'data'
    # Everything in the simple/ prefix will be considered part of this table
    # the prefix may be a regular expression that is compatible with the Rust
    # regex crate
    prefix: '^raw/simple'
    partitions:
      - 'date'
    tablepath: 's3://data/delta/audit_logs'
